# Settings
exclude:
  [
    ".github",
    "Gemfile",
    "Gemfile.lock",
    "build.sh",
    "build-and-serve.sh",
    "build-and-watch.sh",
    "README.md",
  ]
permalink: pretty

url: "https://godotengine.org"

collections_dir: collections
collections:
  article:
    output: true
  event:
    output: false
  showcase:
    output: true
  download:
    output: true
  download_3:
    output: true
    permalink: /download/3.x/:name/
  priorities:
    output: true

# Build collection items with a future date.
future: true

defaults:
  - scope:
      type: "article"
    values:
      layout: "article"
      og_type: "article"
  - scope:
      type: "event"
    values:
      layout: "event"
  - scope:
      type: "showcase"
    values:
      layout: "showcase-item"
  - scope:
      type: "download"
    values:
      layout: "download"
  - scope:
      type: "download_3"
    values:
      layout: "download-3"
  - scope:
      type: "download_archive"
    values:
      layout: "download-archive"
  - scope:
      type: "mirrorlist"
    values:
      layout: "mirrorlist"

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  # - jekyll-multiple-languages-plugin

# Internationalization
languages: ["en", "es"]
exclude_from_localizations: ["assets", "storage"]
default_lang: "en"

# Pagination (used by the blog)
pagination:
  enabled: true
  debug: false

  collection: "article"
  per_page: 24
  sort_field: "date"
  sort_reverse: true
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  title: ":title - Page :num"
  permalink: "/:num/"
  category: "posts"
  tag: ""
  locale: ""

# .scss generation
sass:
  sass_dir: _sass
  style: compressed
