defaults:
  4:
    templates: export_templates.tpz
    editor:
      android.apk: android_editor.apk
      linux.64: linux.x86_64.zip
      linux.32: linux.x86_32.zip
      linux.arm64: linux.arm64.zip
      linux.arm32: linux.arm32.zip
      macos.universal: macos.universal.zip
      windows.64: win64.exe.zip
      windows.32: win32.exe.zip
      web: web_editor.zip
    extras:
      aar_library: template_release.aar

    mono:
      templates: mono_export_templates.tpz
      editor:
        linux.64: mono_linux_x86_64.zip
        linux.32: mono_linux_x86_32.zip
        linux.arm64: mono_linux_arm64.zip
        linux.arm32: mono_linux_arm32.zip
        macos.universal: mono_macos.universal.zip
        windows.64: mono_win64.zip
        windows.32: mono_win32.zip

  3:
    templates: export_templates.tpz
    editor:
      android.apk: android_editor.apk
      linux.64: x11.64.zip
      linux.32: x11.32.zip
      macos.universal: osx.universal.zip
      windows.64: win64.exe.zip
      windows.32: win32.exe.zip
      linux_server.headless.64: linux_headless.64.zip
      linux_server.64: linux_server.64.zip
      web: web_editor.zip
    extras:
      aar_library: release.aar

    mono:
      templates: mono_export_templates.tpz
      editor:
        linux.64: mono_x11_64.zip
        linux.32: mono_x11_32.zip
        macos.universal: mono_osx.universal.zip
        windows.64: mono_win64.zip
        windows.32: mono_win32.zip
        linux_server.headless.64: mono_linux_headless_64.zip
        linux_server.64: mono_linux_server_64.zip
      extras:
        aar_library: mono.release.aar

  2:
    templates: export_templates.tpz
    editor:
      linux.64: x11.64.zip
      linux.32: x11.32.zip
      macos.universal: osx.fat.zip
      windows.64: win64.exe.zip
      windows.32: win32.exe.zip
      linux_server.64: linux_server.64.zip

  1:
    templates: export_templates.tpz
    editor:
      linux.64: x11.64.zip
      linux.32: x11.32.zip
      macos.universal: osx32.zip
      windows.64: win64.exe.zip
      windows.32: win32.exe.zip
      linux_server.64: linux_server.64.zip

overrides:
  # Mono version of Godot 4 was only introduced in 4.0 alpha 17.
  - version: 4
    range:
      - "4.0-alpha1"
      - "4.0-alpha16"
    config:
      templates: export_templates.tpz
      editor:
        android.apk: android_editor.apk
        linux.64: linux.x86_64.zip
        linux.32: linux.x86_32.zip
        macos.universal: macos.universal.zip
        windows.64: win64.exe.zip
        windows.32: win32.exe.zip
        web: web_editor.zip
      extras:
        aar_library: template_release.aar

  # Godot 4.2 beta 5 introduced Linux ARM builds.
  - version: 4
    range:
      - "4.0-alpha17"
      - "4.2-beta4"
    config:
      templates: export_templates.tpz
      editor:
        android.apk: android_editor.apk
        linux.64: linux.x86_64.zip
        linux.32: linux.x86_32.zip
        macos.universal: macos.universal.zip
        windows.64: win64.exe.zip
        windows.32: win32.exe.zip
        web: web_editor.zip
      extras:
        aar_library: template_release.aar

      mono:
        templates: mono_export_templates.tpz
        editor:
          linux.64: mono_linux_x86_64.zip
          linux.32: mono_linux_x86_32.zip
          macos.universal: mono_macos.universal.zip
          windows.64: mono_win64.zip
          windows.32: mono_win32.zip
