name: Continuous integration
on:
  - push
  - pull_request

jobs:
  test:
    name: Validate formatting and setup
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint and format CSS
        run: |
          npm ci
          npm run lint

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          tools: composer:v2
          extensions: curl, fileinfo, gd, mbstring, openssl, pdo, pdo_mysql, xml, zip
          # Disable Xdebug to improve performance.
          coverage: none

      - name: Set up MySQL and install OctoberCMS
        run: |
          sudo systemctl start mysql
          echo -e '[client]\nuser="root"\npassword="root"' > "$HOME/.my.cnf"

          mysql -e "CREATE DATABASE IF NOT EXISTS october;"
          # https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

          # Explicitly allow all plugins to run scripts during installation.
          composer config -g allow-plugins true

          mkdir -p october
          composer create-project october/october ./october "v1.0.474" --no-dev
          pushd october

          php artisan key:generate

          # Copy project files.
          cp -r ../themes/* themes
          cp -r ../docker/php/config/* config
          # Fix up the config for CI.
          sed -i "s/'host'       => 'mariadb'/'host'       => 'localhost'/g" config/database.php
          sed -i "s/'username'   => 'godot'/'username'   => 'root'/g" config/database.php
          sed -i "s/'password'   => 'godot'/'password'   => 'root'/g" config/database.php

          php artisan october:up
          php artisan october:fresh

          php artisan plugin:install paulvonzimmerman.patreon
          php artisan plugin:install pikanji.agent
          php artisan plugin:install rainlab.blog
          php artisan plugin:install rainlab.translate
          php artisan plugin:install sobored.rss

          cp -r ../plugins/* plugins
          composer update -d ./plugins/godotengine/i18n
          php artisan october:up

      - name: Run Lighthouse CI
        run: |
          npm install @lhci/cli@0.6.x
          npx lhci autorun
